# Generated by Django 5.2.8 on 2025-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('math_performance', models.FloatField(help_text='Score from 0 to 10')),
                ('reading_writing_performance', models.FloatField(help_text='Score from 0 to 10')),
                ('eligible_for_support', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
