# Generated by Django 5.2.8 on 2025-11-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('CR', 'Critically Endangered'), ('EN', 'Endangered'), ('VU', 'Vulnerable'), ('NT', 'Near Threatened'), ('LC', 'Least Concern'), ('DD', 'Data Deficient'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], max_length=2)),
                ('pop_size', models.CharField(blank=True, max_length=100, null=True)),
                ('trend', models.CharField(blank=True, choices=[('Increasing', 'Increasing'), ('Decreasing', 'Decreasing'), ('Stable', 'Stable'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('decline_rate', models.FloatField(blank=True, help_text='Decline rate in percentage', null=True)),
                ('range_size', models.CharField(blank=True, help_text='Range size in km²', max_length=100, null=True)),
                ('locations', models.CharField(blank=True, max_length=100, null=True)),
                ('fragmented', models.CharField(blank=True, max_length=50, null=True)),
                ('threats', models.TextField(blank=True, null=True)),
                ('extinct_prob', models.FloatField(blank=True, help_text='Extinction probability in percentage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['animal_name'],
            },
        ),
    ]
